Added support for HFiles in Docker image
senx/warp10-docker pull request #104
Opened 2022-05-20 08:59 UTC by hbs

2022-06-03 14:28 UTC, steven-gueguen requested changes

2022-06-03 14:28 UTC, steven-gueguen commented on Dockerfile
>  LABEL author="SenX S.A.S."
Please update copyright date

2022-06-03 14:35 UTC, steven-gueguen approved these changes

2022-06-07 09:20 UTC, randomboolean approved these changes

2022-06-07 09:50 UTC, merged